version: 2
jobs:
  instruqt-validate:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Validate
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track validate..."
            for dir in $(ls -d /root/project/instruqt-tracks/*); do
              cd $dir && instruqt track validate
            done
  instruqt-test-oss-aws:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/terraform-build-aws
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
  instruqt-test-oss-azure:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/terraform-build-azure
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
  instruqt-test-cloud-aws:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/terraform-cloud-aws
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
  instruqt-test-cloud-azure:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/terraform-cloud-azure
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
  instruqt-test-cloud-gcp:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/terraform-cloud-gcp
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
  instruqt-test-sentinel:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track test..."
            cd /root/project/instruqt-tracks/sentinel-for-terraform
            instruqt track test --skip-fail-check
            echo "Running instruqt track push..."
            instruqt track push --force
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - instruqt-validate
      - instruqt-test-oss-aws:
          requires:
            - instruqt-validate
      - instruqt-test-oss-azure:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-aws:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-azure:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-gcp:
          requires:
            - instruqt-validate
      - instruqt-test-sentinel:
          requires:
            - instruqt-validate
  nightly-build:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - instruqt-validate
      - instruqt-test-oss-aws:
          requires:
            - instruqt-validate
      - instruqt-test-oss-azure:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-aws:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-azure:
          requires:
            - instruqt-validate
      - instruqt-test-cloud-gcp:
          requires:
            - instruqt-validate
      - instruqt-test-sentinel:
          requires:
            - instruqt-validate
